name: ROS2 install test
on:
  push:
    branches:
      - master
    paths:
      - "run.sh"
      - "tutorial.sh"
      - ".github/workflows/main.yml"
  pull_request:
    branches:
      - master
    paths:
      - "run.sh"
      - "tutorial.sh"
      - ".github/workflows/main.yml"
  schedule:
    - cron: "0 1 * * 1"

jobs:
  foxy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Run the install script
        run: |
          sed -e 's/^\(CHOOSE_ROS_DISTRO=.*\)/#\1\nCHOOSE_ROS_DISTRO=foxy/g' -i run.sh
          ./run.sh
      - name: Run the test script
        run: |
          sed -e 's/^\(ROS_DISTRO=.*\)/#\1\nROS_DISTRO=foxy/g' -i tutorial.sh
          bash <(head -n -2 ./tutorial.sh)

  galactic:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Run the install script
        run: |
          sed -e 's/^\(CHOOSE_ROS_DISTRO=.*\)/#\1\nCHOOSE_ROS_DISTRO=galactic/g' -i run.sh
          ./run.sh
      - name: Run the test script
        run: |
          sed -e 's/^\(ROS_DISTRO=.*\)/#\1\nROS_DISTRO=galactic/g' -i tutorial.sh
          bash <(head -n -2 ./tutorial.sh)
