version: 2
jobs:
  foxy:
    docker:
    - image: tiryoh/ubuntu:focal-dev
    steps:
    - checkout
    - run:
        name: Prepare Install
        command: sudo apt-get update && sudo DEBIAN_FRONTEND=noninteractive apt-get install keyboard-configuration
    - run:
        name: Install
        command: sed -e 's/^\(CHOOSE_ROS_DISTRO=.*\)/#\1\nCHOOSE_ROS_DISTRO=foxy/g' -i run.sh && ./run.sh
    - run:
        name: Test
        command: sed -e 's/^\(ROS_DISTRO=.*\)/#\1\nROS_DISTRO=foxy/g' -i tutorial.sh &&  bash -c "$(head -n -2 ./tutorial.sh && echo 'which ros2')"
  galactic:
    docker:
    - image: tiryoh/ubuntu:focal-dev
    steps:
    - checkout
    - run:
        name: Prepare Install
        command: sudo apt-get update && sudo DEBIAN_FRONTEND=noninteractive apt-get install keyboard-configuration
    - run:
        name: Install
        command: sed -e 's/^\(CHOOSE_ROS_DISTRO=.*\)/#\1\nCHOOSE_ROS_DISTRO=galactic/g' -i run.sh && ./run.sh
    - run:
        name: Test
        command: sed -e 's/^\(ROS_DISTRO=.*\)/#\1\nROS_DISTRO=galactic/g' -i tutorial.sh &&  bash -c "$(head -n -2 ./tutorial.sh && echo 'which ros2')"

workflows:
  version: 2
  commit-workflow:
    jobs:
      - foxy
      - galactic

  scheduled-workflow:
    triggers:
      - schedule:
          cron: "0 1 * * 1"
          filters:
            branches:
              only:
                - master
    jobs:
      - foxy
      - galactic
